-- Add missing columns to tables
-- Run this in Supabase SQL Editor

-- Add missing columns to leads table
ALTER TABLE leads ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS mobile VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_category VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS account_type VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS industry VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS job_title VARCHAR(150);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS budget DECIMAL(15, 2);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS website VARCHAR(255);

-- Add missing columns to contacts table
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS mobile VARCHAR(50);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS account_id UUID REFERENCES accounts(id);

-- Add missing columns to accounts table
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS website VARCHAR(255);

-- Add missing columns to deals table
ALTER TABLE deals ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS account_id UUID REFERENCES accounts(id);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS contact_name VARCHAR(200);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS forecast VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS lead_source VARCHAR(100);
