-- ============================================================
-- LEADS TABLE MIGRATION - Add Extended Fields
-- Safe to run multiple times (uses IF NOT EXISTS)
-- ============================================================

-- Lead Information (Extended) - 9 fields
ALTER TABLE leads ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS mobile VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS mobile_alternate VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS phone_alternate VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS campaign_source VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS website VARCHAR(500);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS account_type VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_category VARCHAR(50);

-- Order Info - 13 fields
ALTER TABLE leads ADD COLUMN IF NOT EXISTS product_list VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS type_of_order VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS billing_delivery_date DATE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS order_product_details TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS payment VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS po_number_or_mail_confirmation VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS brand VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS orc_amount NUMERIC(15,2);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS product_warranty VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS ship_by VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS special_instruction TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS third_party_delivery_address TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS billing_company VARCHAR(255);

-- Forms Info - 7 fields
ALTER TABLE leads ADD COLUMN IF NOT EXISTS enter_product_details TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS rental_duration VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS product_configuration TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS bandwidth_required VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS product_name_and_part_number VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS specifications TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS form_name VARCHAR(100);

-- Billing Address - 5 fields
ALTER TABLE leads ADD COLUMN IF NOT EXISTS billing_street VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS billing_city VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS billing_state VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS billing_country VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS billing_zip_code VARCHAR(20);

-- Description Info - 11 fields
ALTER TABLE leads ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_time VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS product_name VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS receiver_mobile_number VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS subject VARCHAR(500);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS sender_landline_no VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS sender_landline_no_alt VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS call_duration VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_type VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS query_id VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS mcat_name VARCHAR(100);

-- Lead Image - 1 field
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_image TEXT;
