import React from 'react';
import {
  Users, Calendar, Building2, Layers, TrendingUp, Package,
  Target, Award, ShoppingCart, BarChart3, UserCheck, CheckSquare,
  Briefcase, ListTodo, CalendarClock, UserPlus, Filter
} from 'lucide-react';
import { WidgetMetadata, DashboardPreferences } from '@/types';
import { lazyWithRetry } from '@/utils/lazyWithRetry';

// Widget components will be imported as we create them
// import { SalesTeamWidget } from '@/components/dashboard/widgets/SalesTeamWidget';
// ... etc

export const WIDGET_REGISTRY: Record<string, WidgetMetadata> = {
  // ── Personal "My" widgets (shown first) ────────────────────
  'my-kpi-cards': {
    id: 'my-kpi-cards',
    label: 'My KPIs',
    description: 'Personal KPI summary cards',
    category: 'both',
    icon: <Briefcase className="w-4 h-4" />,
    defaultVisible: true,
    defaultOrder: 1,
    gridSpan: 'full',
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/MyKpiCardsWidget').then(m => ({ default: m.MyKpiCardsWidget }))),
  },
  'my-open-tasks': {
    id: 'my-open-tasks',
    label: 'My Open Tasks',
    description: 'Your pending and in-progress tasks',
    category: 'tasks',
    icon: <ListTodo className="w-4 h-4" />,
    defaultVisible: true,
    defaultOrder: 2,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/MyOpenTasksWidget').then(m => ({ default: m.MyOpenTasksWidget }))),
    navigateTo: 'tasks',
  },
  'my-meetings': {
    id: 'my-meetings',
    label: 'My Meetings',
    description: 'Your upcoming meetings',
    category: 'tasks',
    icon: <CalendarClock className="w-4 h-4" />,
    defaultVisible: true,
    defaultOrder: 3,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/MyMeetingsWidget').then(m => ({ default: m.MyMeetingsWidget }))),
    navigateTo: 'calendar',
  },
  'todays-leads': {
    id: 'todays-leads',
    label: "Today's Leads",
    description: 'Leads received today',
    category: 'presales',
    icon: <UserPlus className="w-4 h-4" />,
    defaultVisible: true,
    defaultOrder: 4,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/TodaysLeadsWidget').then(m => ({ default: m.TodaysLeadsWidget }))),
    navigateTo: 'leads',
  },
  'deals-closing-this-month': {
    id: 'deals-closing-this-month',
    label: 'Deals Closing This Month',
    description: 'Deals expected to close this month',
    category: 'presales',
    icon: <Briefcase className="w-4 h-4" />,
    defaultVisible: true,
    defaultOrder: 5,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/DealsClosingThisMonthWidget').then(m => ({ default: m.DealsClosingThisMonthWidget }))),
    navigateTo: 'deals',
  },
  'my-pipeline-funnel': {
    id: 'my-pipeline-funnel',
    label: 'My Pipeline By Stage',
    description: 'Funnel view of your deal pipeline',
    category: 'presales',
    icon: <Filter className="w-4 h-4" />,
    defaultVisible: true,
    defaultOrder: 6,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/MyPipelineFunnelWidget').then(m => ({ default: m.MyPipelineFunnelWidget }))),
    navigateTo: 'deals',
  },
  'sales-users-targets': {
    id: 'sales-users-targets',
    label: 'Sales Users Targets',
    description: 'Monthly targets vs achievements per user',
    category: 'analytics',
    icon: <Target className="w-4 h-4" />,
    defaultVisible: true,
    defaultOrder: 7,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/SalesUsersTargetsWidget').then(m => ({ default: m.SalesUsersTargetsWidget }))),
  },

  // ── Analytics & team widgets ───────────────────────────────
  'sales-team': {
    id: 'sales-team',
    label: 'Sales Team',
    description: 'Performance tracker for sales team',
    category: 'postsales',
    icon: <Users className="w-4 h-4" />,
    requiredView: 'postsales',
    defaultVisible: true,
    defaultOrder: 8,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/SalesTeamWidget').then(m => ({ default: m.SalesTeamWidget }))),
    navigateTo: 'sales-entry',
  },
  'monthly': {
    id: 'monthly',
    label: 'Monthly Revenue',
    description: 'Last 6 months revenue trend',
    category: 'postsales',
    icon: <Calendar className="w-4 h-4" />,
    requiredView: 'postsales',
    defaultVisible: true,
    defaultOrder: 9,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/MonthlyWidget').then(m => ({ default: m.MonthlyWidget }))),
    navigateTo: 'sales-entry',
  },
  'partners': {
    id: 'partners',
    label: 'Accounts',
    description: 'Account statistics and sales',
    category: 'postsales',
    icon: <Building2 className="w-4 h-4" />,
    requiredView: 'postsales',
    defaultVisible: true,
    defaultOrder: 10,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/PartnersWidget').then(m => ({ default: m.PartnersWidget }))),
    navigateTo: 'partners',
  },
  'pipeline': {
    id: 'pipeline',
    label: 'Deal Kanban',
    description: 'Stage distribution of deals',
    category: 'presales',
    icon: <Layers className="w-4 h-4" />,
    requiredView: 'presales',
    defaultVisible: true,
    defaultOrder: 11,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/PipelineWidget').then(m => ({ default: m.PipelineWidget }))),
    navigateTo: 'deals',
  },
  'growth': {
    id: 'growth',
    label: 'Growth Metrics',
    description: 'Performance and growth indicators',
    category: 'postsales',
    icon: <TrendingUp className="w-4 h-4" />,
    requiredView: 'postsales',
    defaultVisible: true,
    defaultOrder: 12,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/GrowthWidget').then(m => ({ default: m.GrowthWidget }))),
    navigateTo: 'sales-entry',
  },
  'products': {
    id: 'products',
    label: 'Products',
    description: 'Portfolio performance by product',
    category: 'postsales',
    icon: <Package className="w-4 h-4" />,
    requiredView: 'postsales',
    defaultVisible: true,
    defaultOrder: 13,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/ProductsWidget').then(m => ({ default: m.ProductsWidget }))),
    navigateTo: 'sales-entry',
  },
  'leads': {
    id: 'leads',
    label: 'Leads',
    description: 'Lead funnel analysis',
    category: 'presales',
    icon: <Target className="w-4 h-4" />,
    requiredView: 'presales',
    defaultVisible: true,
    defaultOrder: 14,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/LeadsWidget').then(m => ({ default: m.LeadsWidget }))),
    navigateTo: 'leads',
  },
  'assignee-summary': {
    id: 'assignee-summary',
    label: 'Assignee Summary',
    description: 'Per-user assigned accounts, leads, deals & sales',
    category: 'analytics',
    icon: <UserCheck className="w-4 h-4" />,
    defaultVisible: true,
    defaultOrder: 15,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/AssigneeSummaryWidget').then(m => ({ default: m.AssigneeSummaryWidget }))),
  },
  'top-partners': {
    id: 'top-partners',
    label: 'Top Accounts',
    description: 'Revenue rankings by account',
    category: 'postsales',
    icon: <Award className="w-4 h-4" />,
    requiredView: 'postsales',
    defaultVisible: true,
    defaultOrder: 16,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/TopPartnersWidget').then(m => ({ default: m.TopPartnersWidget }))),
    navigateTo: 'partners',
  },
  'recent-sales': {
    id: 'recent-sales',
    label: 'Recent Sales',
    description: 'Latest transactions',
    category: 'postsales',
    icon: <ShoppingCart className="w-4 h-4" />,
    requiredView: 'postsales',
    defaultVisible: true,
    defaultOrder: 17,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/RecentSalesWidget').then(m => ({ default: m.RecentSalesWidget }))),
    navigateTo: 'sales-entry',
  },
  'revenue-trend': {
    id: 'revenue-trend',
    label: 'Revenue Trend',
    description: 'Monthly revenue chart',
    category: 'analytics',
    icon: <BarChart3 className="w-4 h-4" />,
    requiredView: 'postsales',
    defaultVisible: true,
    defaultOrder: 18,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/RevenueTrendWidget').then(m => ({ default: m.RevenueTrendWidget }))),
    navigateTo: 'sales-entry',
  },
  'pipeline-chart': {
    id: 'pipeline-chart',
    label: 'Kanban Chart',
    description: 'Deal stage visualization',
    category: 'analytics',
    icon: <Layers className="w-4 h-4" />,
    requiredView: 'presales',
    defaultVisible: true,
    defaultOrder: 19,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/PipelineChartWidget').then(m => ({ default: m.PipelineChartWidget }))),
    navigateTo: 'deals',
  },
  'leads-distribution': {
    id: 'leads-distribution',
    label: 'Leads Distribution',
    description: 'Lead stage distribution chart',
    category: 'analytics',
    icon: <Target className="w-4 h-4" />,
    requiredView: 'presales',
    defaultVisible: true,
    defaultOrder: 20,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/LeadsDistributionWidget').then(m => ({ default: m.LeadsDistributionWidget }))),
    navigateTo: 'leads',
  },
  'tasks': {
    id: 'tasks',
    label: 'Tasks',
    description: 'Task completion and status overview',
    category: 'analytics',
    icon: <CheckSquare className="w-4 h-4" />,
    defaultVisible: true,
    defaultOrder: 21,
    component: lazyWithRetry(() => import('@/components/features/dashboard/widgets/TasksWidget').then(m => ({ default: m.TasksWidget }))),
    navigateTo: 'tasks',
  },
};

export const getDefaultPreferences = (): DashboardPreferences => ({
  widgets: Object.values(WIDGET_REGISTRY).map(w => ({
    id: w.id,
    visible: w.defaultVisible,
    order: w.defaultOrder,
  })),
  lastModified: new Date().toISOString(),
});

export const getWidgetsByCategory = (category: string) => {
  return Object.values(WIDGET_REGISTRY).filter(w => w.category === category);
};
